services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: vpn
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${PROXY_PORT}:8888/tcp # HTTP proxy
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - TZ=Europe/Helsinki
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - HTTPPROXY=on
      - HTTPPROXY_USER=${PROXY_USER}
      - HTTPPROXY_PASSWORD=${PROXY_PASSWORD}
